#!/usr/bin/env bash
# check-provenance.sh — audit external/ for missing or malformed front matter,
# and flag files that leaked out of scope.
#
# Usage: scripts/check-provenance.sh
# Exit 0 = clean, 1 = problems found.
#
# POSTURE: this validates that a file still looks GENERATED by new-external.sh.
# It is not a YAML parser and does not try to be one. Six rounds of review were
# spent adding one special case per exploit — quoted-empty, plain nulls, inline
# comments, escaped whitespace, block scalars, duplicate keys, junk tails — and
# each fix left the next shape open, because a deny-list of observed exploits
# can never be complete. What IS complete is YAML's own indicator set, which is
# closed and documented, so the plain-scalar check below enumerates that rather
# than a list of things somebody happened to try.
#
# Run scripts/selftest.sh after any change here. It carries every shape those
# rounds found; if a change breaks one, the corpus says so in a second.

set -uo pipefail

root="$PWD"
while [[ "$root" != "/" && ! -d "$root/external" ]]; do root="$(dirname "$root")"; done
if [[ ! -d "$root/external" ]]; then
  printf 'ERROR: no external/ directory found above %s\n' "$PWD" >&2; exit 1
fi

# perl does the scalar decoding and the normalising read. Without it both would
# fail toward "Clean", so refuse up front rather than degrade silently.
if ! command -v perl >/dev/null 2>&1; then
  printf 'ERROR: perl is required (scalar decoding and normalised reads).\n' >&2
  exit 1
fi

# ---------------------------------------------------------------- enumeration

# -print0 because a filename may contain a newline: line-delimited, such a path
# split into two bogus reads and was dropped by both loops. -iname over three
# extensions because `-name '*.md'` silently skipped Notes.MD and notes.txt.
# -L so a symlinked file or directory is followed rather than ignored.
# Enumerated ONCE into temp files, because `find`'s exit status is invisible
# through process substitution: a symlink cycle under external/ printed its
# error to stderr, the loop consumed whatever had been listed, and the script
# still exited 0 with "Provenance clean" over an audit it knew was incomplete.
TEXTLIST="$(mktemp)"; OTHERLIST="$(mktemp)"; FINDERR="$(mktemp)"
trap 'rm -f "$TEXTLIST" "$OTHERLIST" "$FINDERR"' EXIT
enumerate_failed=0
find -L "$root/external" -type f \
  \( -iname '*.md' -o -iname '*.markdown' -o -iname '*.txt' \) -print0 \
  2>"$FINDERR" | LC_ALL=C sort -z > "$TEXTLIST" || enumerate_failed=1
[[ -s "$FINDERR" ]] && enumerate_failed=1
find -L "$root/external" -type f \
  ! -iname '*.md' ! -iname '*.markdown' ! -iname '*.txt' ! -name '.*' -print0 \
  2>>"$FINDERR" | LC_ALL=C sort -z > "$OTHERLIST" || enumerate_failed=1
[[ -s "$FINDERR" ]] && enumerate_failed=1

# A path may contain a newline, which would split or forge a report line.
disp() { printf '%s' "$1" | perl -pe 's/\\/\\\\/g; s/\n/\\n/g; s/\t/\\t/g; s/\r/\\r/g'; }

# Read once, normalised. A UTF-8 BOM or CRLF changes nothing about what a file
# MEANS, but either made intact front matter report as "no front matter" — a
# verdict that is false about the file. Byte-level escapes: perl reads bytes
# here, so the BOM is \xEF\xBB\xBF, not \x{FEFF}.
read_normalised() { perl -0777 -pe 's/^\xEF\xBB\xBF//; s/\r\n/\n/g' "$1"; }

# ------------------------------------------------------------ scalar decoding

# What follows the closing quote of a quoted scalar. Exit 1 if never closed.
#
# Tracks escape STATE rather than the previous byte. A `prev == backslash`
# look-back cannot tell `\"` from `\\"`, so a citation ending in a backslash —
# which new-external.sh itself produces — was rejected as "never closed", while
# `"https://good\\" junk "` was accepted. Note the pattern must be "\\" in
# DOUBLE quotes (one literal backslash); a single-quoted '\\' is two characters
# and never matches, which silently disables escape tracking altogether.
yaml_quoted_tail() {
  local v=$1 q=${1:0:1} i=1 c esc=0
  while (( i < ${#v} )); do
    c=${v:i:1}
    if (( esc )); then
      esc=0
    elif [[ "$c" == "\\" && "$q" == '"' ]]; then
      esc=1
    elif [[ "$c" == "$q" ]]; then
      # '' is the only way YAML admits an apostrophe inside single quotes.
      if [[ "$q" == "'" && "${v:i+1:1}" == "'" ]]; then i=$((i+2)); continue; fi
      printf '%s' "${v:i+1}"; return 0
    fi
    i=$((i+1))
  done
  return 1
}

# Decode a scalar far enough to tell "has a value" from "has none".
yaml_scalar() {
  local v=$1 out="" i c esc=0
  case "$v" in
    \"*)
      i=1
      while (( i < ${#v} )); do
        c=${v:i:1}
        if (( esc )); then esc=0; out+="$c"
        elif [[ "$c" == "\\" ]]; then esc=1; out+="$c"
        elif [[ "$c" == '"' ]]; then break
        else out+="$c"; fi
        i=$((i+1))
      done
      # ONE left-to-right pass. Six ordered substitutions each re-scanned the
      # previous one's output, so a generator-escaped `\\` was consumed by a
      # later pass and `C:\temp\tds.pdf` decoded to `C:<TAB>emp<TAB>ds.pdf` —
      # rejecting the generator's own output as empty. Do not split this up.
      printf '%s' "$out" | perl -pe 's{\\(U[0-9a-fA-F]{8}|u[0-9a-fA-F]{4}|x[0-9a-fA-F]{2}|.)}{ my $e=$1;
        $e=~/^[Uux](.+)$/ ? chr(hex($1)) :
        $e eq "0" ? " " : $e eq "a" ? "\a" : $e eq "b" ? "\b" : $e eq "t" ? "\t" :
        $e eq "n" ? "\n" : $e eq "v" ? "\013" : $e eq "f" ? "\f" : $e eq "r" ? "\r" :
        $e eq "e" ? "\033" : $e eq "N" ? "\x{85}" : $e eq "_" ? "\x{a0}" :
        $e eq "L" ? "\x{2028}" : $e eq "P" ? "\x{2029}" : $e }ge'
      return ;;
    \'*)
      i=1
      while (( i < ${#v} )); do
        c=${v:i:1}
        if [[ "$c" == "'" ]]; then
          if [[ "${v:i+1:1}" == "'" ]]; then out+="'"; i=$((i+2)); continue; fi
          break
        fi
        out+="$c"; i=$((i+1))
      done
      printf '%s' "$out"; return ;;
  esac
  # Plain scalar: '#' opens a comment at the start or after whitespace, and
  # only then does a null spelling mean anything.
  [[ "$v" == '#'* ]] && { printf ''; return; }
  v="${v%%[[:space:]]#*}"
  v="${v%"${v##*[![:space:]]}"}"
  case "$v" in null|Null|NULL|'~') v="" ;; esac
  printf '%s' "$v"
}

problems=0
checked=0

while IFS= read -r -d '' f; do
  [[ -f "$f" ]] || continue
  checked=$((checked+1))
  rel="$(disp "${f#"$root"/}")"

  # A NUL is removed by command substitution, so it must be caught on the raw
  # file: otherwise bash prints a warning, the validator never sees it, and the
  # script exits 0 on YAML every parser rejects.
  if ! perl -0777 -ne 'exit(/\0/ ? 1 : 0)' "$f"; then
    printf '%s\n    contains a NUL byte — not parseable YAML\n' "$rel"
    problems=$((problems+1))
    continue
  fi

  content="$(read_normalised "$f")"
  first="${content%%$'\n'*}"

  if [[ "$first" != "---" ]]; then
    printf '%s\n    no front matter — untrusted, do not read from it\n' "$rel"
    problems=$((problems+1))
    continue
  fi

  # The front matter must actually CLOSE, before the first blank line. A bare
  # "does a second --- exist?" test is satisfied by an ordinary markdown
  # horizontal rule in the body, which is the same hole again.
  if ! awk 'NR==1{next} /^---[[:space:]]*$/{ok=1;exit} /^[[:space:]]*$/{exit} END{exit ok?0:1}' <<<"$content"; then
    printf '%s\n    front matter never closed — no terminating "---" line\n' "$rel"
    problems=$((problems+1))
    continue
  fi

  fm="$(awk 'NR==1&&/^---[[:space:]]*$/{next} /^---[[:space:]]*$/{exit} {print}' <<<"$content")"

  note=""
  add_note() { note="${note}${note:+; }$1"; }

  # Raw control characters and invalid UTF-8 make the block unloadable YAML,
  # and libyaml refuses the whole file — but a line-oriented reader sees text.
  # An ALLOW-list of what YAML permits, not a deny-list of C0+DEL: a deny-list
  # leaves C1 and invalid UTF-8 open, which is the identical failure again.
  if ! printf '%s' "$fm" | perl -e 'use Encode(); binmode(STDIN,":raw");
    my $s = do { local $/; <STDIN> }; $s = "" unless defined $s;
    my $d = eval { Encode::decode("UTF-8",$s,Encode::FB_CROAK()) }; exit 1 unless defined $d;
    for my $c (split //,$d) { my $o=ord $c;
      next if $o==0x09||$o==0x0A||$o==0x0D; next if $o>=0x20 && $o<=0x7E;
      next if $o==0x85; next if $o>=0xA0 && $o<=0xD7FF;
      next if $o>=0xE000 && $o<=0xFFFD; next if $o>=0x10000 && $o<=0x10FFFF; exit 1 }
    exit 0'; then
    add_note "front matter contains a control character or invalid UTF-8 — rewrite with new-external.sh"
  fi

  # Every non-blank line must be one of the four keys. YAML needs colon+space
  # (or colon at end of line) to open a mapping: `source:https://x` and three
  # more unspaced lines are ONE plain scalar with zero keys, and that audited
  # Clean. Keyed on [[:space:]] because a tab after the colon is valid.
  while IFS= read -r line; do
    [[ -z "${line//[[:space:]]/}" ]] && continue
    case "$line" in
      source:|retrieved:|trust:|scope:) ;;
      source:[[:space:]]*|retrieved:[[:space:]]*|trust:[[:space:]]*|scope:[[:space:]]*) ;;
      *) add_note "unsupported line: $(disp "$line")" ;;
    esac
  done <<<"$fm"

  for key in source retrieved trust scope; do
    cnt="$(grep -cE "^${key}:([[:space:]]|$)" <<<"$fm")"
    if (( cnt == 0 )); then add_note "${key}: absent"; continue; fi
    # Duplicates are ambiguous by definition — readers variously reject them or
    # keep the last — and reading only the first silently validated a good
    # value followed by `source: null`.
    if (( cnt > 1 )); then add_note "${key}: repeated ${cnt}x"; continue; fi
    raw="$(sed -n "s/^${key}:[[:space:]]*//p" <<<"$fm")"
    case "$raw" in
      \"*|\'*)
        # YAML 1.2 §5.7 defines exactly these escapes; everything else makes
        # the document invalid. Walked STATEFULLY, consuming each escape as a
        # pair — a regex that inspects every backslash independently reads the
        # second half of `\\q` as the start of an unsupported `\q`, so the
        # generator's own `"C:\\query\\vendor.pdf"` failed its own audit.
        # (An earlier corpus case used `C:\\temp\\tds.pdf` and passed by luck:
        # `t` happens to be a valid escape letter and `q` does not.)
        if [[ "${raw:0:1}" == '"' ]]; then
          perl -e '
            my $s = shift; my $i = 1; my $n = length $s;
            while ($i < $n) {
              my $c = substr($s,$i,1);
              exit 0 if $c eq q{"};
              if ($c eq "\\") {
                my $e = substr($s,$i+1,1);
                if ($e =~ m{^[0abtnvfre "/\\N_LP]$}) { $i += 2; next }
                if ($e eq "x" && substr($s,$i+2,2) =~ /^[0-9a-fA-F]{2}$/) { $i += 4; next }
                if ($e eq "u" && substr($s,$i+2,4) =~ /^([0-9a-fA-F]{4})$/) {
                  my $cp = hex($1); exit 2 if $cp >= 0xD800 && $cp <= 0xDFFF; $i += 6; next }
                if ($e eq "U" && substr($s,$i+2,8) =~ /^([0-9a-fA-F]{8})$/) {
                  my $cp = hex($1);
                  exit 2 if $cp > 0x10FFFF || ($cp >= 0xD800 && $cp <= 0xDFFF); $i += 10; next }
                exit 1;
              }
              $i++;
            }
            exit 0' "$raw"
          case $? in
            1) add_note "${key}: unsupported escape sequence — YAML defines a fixed set; rewrite with new-external.sh"; continue ;;
            2) add_note "${key}: escape is not a Unicode scalar value (out of range, or a surrogate)"; continue ;;
          esac
        fi
        if tail="$(yaml_quoted_tail "$raw")"; then
          tail="${tail#"${tail%%[![:space:]]*}"}"
          if [[ -n "$tail" && "$tail" != '#'* ]]; then
            add_note "${key}: unexpected text after the quoted value: $(disp "$tail")"; continue
          fi
        else
          add_note "${key}: quoted value is never closed"; continue
        fi ;;
      *)
        # PLAIN scalar. The decoder below only asks "is there text here?", so
        # every YAML form carrying NO value — [] {} !!null &anchor !!str "" —
        # read as content, and forms no parser can load read as content too.
        # This enumerates YAML's SPECIFIED indicator set rather than observed
        # exploits: the indicators are  - ? : # , [ ] { } & * ! | > ' " % @ `
        # and every one not handled by an arm above appears here. `-`, `?` and
        # `:` are indicators only when bare or before whitespace, so `-foo`,
        # `?foo`, `:foo` and `a:b` remain legal plain scalars and still pass.
        case "$raw" in
          []\[{}\,\&\*\!%@\`\|\>]*)
            add_note "${key}: value starts with a YAML indicator — quote it, or rewrite with new-external.sh"; continue ;;
          [-?:]|[-?:][[:space:]]*)
            add_note "${key}: value is a bare YAML indicator — quote it, or rewrite with new-external.sh"; continue ;;
        esac
        # ": " reopens the line as a nested mapping and a trailing ":" makes it
        # a key — both unloadable. The separator is colon + ANY whitespace, so
        # colon-TAB counts too — but only after a colon: a bare tab inside a
        # plain scalar (`Vendor<TAB>TDS`, ordinary pasted text) is perfectly
        # valid YAML, and rejecting it was a false positive, which for this
        # tool is worse than the miss it replaced. Strip a trailing comment
        # first, or `Fiberon # see table 2: page 4` (valid) would trip it.
        plain="${raw%%[[:space:]]#*}"
        plain="${plain%"${plain##*[![:space:]]}"}"
        case "$plain" in
          *": "*|*":"$'\t'*|*:)
            add_note "${key}: unquoted value contains \": \" or ends in \":\" — quote it, or rewrite with new-external.sh"; continue ;;
        esac ;;
    esac
    val="$(yaml_scalar "$raw")"
    if [[ -z "${val//[[:space:]]/}" ]]; then add_note "${key}: empty"; continue; fi
    # A YAML BOOLEAN is never a citation or a scope. Unquoted `true`, `no`,
    # `off` and friends load as booleans, not strings, and there is no reading
    # under which they are provenance — so this is the half of "implicitly
    # typed" worth enforcing. NUMBERS are deliberately still accepted: an
    # unquoted ISBN (9780123456789) or a bare year is a citation someone
    # plausibly writes, and rejecting those would be a false positive, which
    # for this pair of scripts is the worse failure.
    if [[ "$key" == source || "$key" == scope ]] && [[ "${raw:0:1}" != '"' && "${raw:0:1}" != "'" ]]; then
      case "$val" in
        y|Y|yes|Yes|YES|n|N|no|No|NO|true|True|TRUE|false|False|FALSE|on|On|ON|off|Off|OFF)
          add_note "${key}: a YAML boolean is not provenance — quote it if that is the literal text"
          continue ;;
      esac
    fi
    # Both validate the DECODED value; matching serialized text rejected a
    # validly quoted `retrieved: "2026-08-30"`.
    case "$key" in
      retrieved)
        # Shape AND calendar. `2026-02-30` and `2026-99-99` have the right digit
        # layout and are not dates, and this field's whole job is saying when a
        # source was fetched — an impossible one cannot answer that. The app
        # itself hit this on spool dates (GH #372) for the same reason. Leap
        # years handled explicitly rather than trusting a library to reject
        # rather than silently normalise Feb 30 into March.
        if ! printf '%s' "$val" | perl -ne '
              my ($y,$m,$d) = /^(\d{4})-(\d{2})-(\d{2})$/ or exit 1;
              exit 1 if $m < 1 || $m > 12 || $d < 1;
              my @dim = (31,28,31,30,31,30,31,31,30,31,30,31);
              $dim[1] = 29 if ($y % 4 == 0 && $y % 100 != 0) || $y % 400 == 0;
              exit 1 if $d > $dim[$m-1];
              exit 0'; then
          add_note "retrieved is not a real YYYY-MM-DD date: ${val}"
        fi ;;
      trust)
        [[ "$val" == "background" ]] \
          || add_note "trust must be \"background\" in external/ (got: ${val})" ;;
    esac
  done

  if [[ -n "$note" ]]; then
    printf '%s\n    %s\n' "$rel" "$note"
    problems=$((problems+1))
    continue
  fi
done < "$TEXTLIST"

# ------------------------------------------------------------------ leak scan

# Process parameters that must never live in external/ (tier 4).
#
# A HEURISTIC, and deliberately a simple one. It used to strip locators before
# scanning, so that a citation like `.../pa6-cf-bed-temp-chart` did not
# synthesise the phrase "bed temp" once the tr flattens hyphens. That strip
# grew an arm per citation shape over seven review rounds — scheme, POSIX path,
# Windows path, UNC, tilde, bare filename, spaces, escaped quotes, three
# delimiters — and the set never closed, because parsing citation syntax out of
# free prose is open-ended: markdown links, angle brackets and href attributes
# were next. Two of those arms also introduced MISSES while fixing false
# positives, which is the worst possible trade for a scan like this.
#
# So the guessing is gone. What remains is the part that cannot be wrong, plus
# an explicit escape hatch:
#
#   - `source:` is blanked, `scope:` is scanned. That is the field definitions,
#     not a shape heuristic: a source is a citation, a scope is prose.
#   - A bare URL token is dropped. `\S*` stops at whitespace, so it can only
#     ever consume one unbroken token — `foo://nozzle temp 265` keeps its prose.
#   - Anything else that trips the scan wrongly is silenced per file, in the
#     file, with a stated reason.
#
# The trade is deliberate: a body citation whose filename contains
# parameter-like words now flags, and the remedy is one line the reader can
# see. That is better than a regex nobody can audit by eye.
#
# Anchors avoid the bare stems: `shrink` flags "reduces shrinkage anisotropy"
# and `retract` flags "chain retraction in the Doi-Edwards tube model" — both
# legitimate chemistry. `plate` and `extruder` are excluded for the same reason.
PARAM_RE='(nozzle|bed|chamber|hotend) temp|extrusion multiplier|pressure advance|volumetric speed|dry(ing)? (temp|time)|first layer temp|flow ratio|linear advance|k factor|shrinkage compensation|fan speed|retraction (length|distance|speed|[0-9])'
# The reason must contain a non-whitespace character: `[^>]*` accepted
# `<!-- allow-param-smell: -->`, so a reasonless marker silenced a real leak
# while the docs promised it could not. `[^>[:space:]]` then `[^>]*` requires
# at least one real character without allowing a `>` to close the comment early.
ALLOW_RE='<!--[[:space:]]*allow-param-smell:[[:space:]]*[^>[:space:]][^>]*-->'
leaks=0
suppressed=0
while IFS= read -r -d '' f; do
  [[ -f "$f" ]] || continue
  content="$(read_normalised "$f")"

  # The escape hatch. Requires a REASON after the colon, so the marker records
  # why rather than merely silencing; listed in the output so a file cannot opt
  # out invisibly.
  if [[ "$content" =~ $ALLOW_RE ]]; then
    (( suppressed == 0 )) && printf '\nParameter scan suppressed by an in-file marker:\n'
    printf '    %s\n' "$(disp "${f#"$root"/}")"
    suppressed=$((suppressed+1))
    continue
  fi

  # Scan the whole file — front matter and HTML comments included. The comment
  # strip was a blind spot the generator's own template pointed writers into,
  # and one stray "<!--" swallowed everything to the next "-->".
  #
  # `source:` blanked in the FRONT MATTER only: a body line beginning with that
  # word is prose like any other.
  # '-' MUST be last in the tr set: '_-|' is a RANGE (0x5F..0x7C) eating a-z.
  norm="$(printf '%s' "$content" \
          | perl -0777 -pe 's{\A(---\n)(.*?)(\n---[ \t]*\n?)}{
                              my ($o,$fm,$c) = ($1,$2,$3);
                              $fm =~ s{^source:.*$}{source:}gm;
                              "$o$fm$c" }se' \
          | perl -0777 -pe 's{\b[A-Za-z][A-Za-z0-9+.-]*://\S*}{ }g' \
          | tr 'A-Z' 'a-z' | tr '_|:-' '    ' | tr -s '[:space:]' ' ')"
  [[ -z "${norm//[[:space:]]/}" ]] && continue
  if grep -qE "$PARAM_RE" <<<"$norm"; then
    (( leaks == 0 )) && printf '\nPossible processing parameters in external/ (tier 4 must not carry these):\n'
    printf '    %s\n' "$(disp "${f#"$root"/}")"
    printf '      if this is a citation rather than a parameter, add to the file:\n'
    printf '      <!-- allow-param-smell: why this is not a processing value -->\n'
    leaks=$((leaks+1))
  fi
done < "$TEXTLIST"


# Files the schema does not cover — listed, never fatal. SKILL.md says every
# file here carries front matter, but a saved PDF cannot, and failing on one
# would turn a legitimate tree red with no remedy.
unaudited=0
while IFS= read -r -d '' f; do
  (( unaudited == 0 )) && printf '\nNot audited (no provenance schema for these):\n'
  printf '    %s\n' "$(disp "${f#"$root"/}")"
  unaudited=$((unaudited+1))
done < "$OTHERLIST"

# "Checked 0 file(s). Clean." over a non-empty directory is the exact fail-open
# shape this script exists to prevent, and it was reachable four ways.
if (( enumerate_failed )); then
  printf '\nCould not fully enumerate external/ — the audit is INCOMPLETE:\n'
  sed 's/^/    /' "$FINDERR" | head -5
  problems=$((problems+1))
fi

# `ls -A` counted dotfiles that BOTH enumerations deliberately skip, so an
# otherwise-empty external/ holding only Finder's .DS_Store — which appears the
# moment anyone opens the folder — failed with "0 files were audited". The
# guard has to ask the same question the enumerations answer: is there anything
# here that should have been audited or listed?
if (( checked == 0 && unaudited == 0 )) \
   && [[ -n "$(find -L "$root/external" -mindepth 1 ! -name '.*' -print -quit 2>/dev/null)" ]]; then
  printf '\nexternal/ is not empty but 0 files were audited — refusing to report Clean.\n'
  problems=$((problems+1))
fi

printf '\nChecked %d file(s) in external/.\n' "$checked"
if (( problems == 0 && leaks == 0 )); then
  # Deliberately not the bare word "Clean": no regex closes the value-only
  # forms (a settings table, "Print at 265 C"), so certifying the leak scan
  # as conclusive would be a false assurance at zero cost to avoid.
  printf 'Provenance clean. No parameter smells matched (heuristic — tier-4 scope is still your call).\n'
  exit 0
fi
printf '%d provenance problem(s), %d possible parameter leak(s).\n' "$problems" "$leaks"
exit 1
