import { NextResponse } from "next/server";
import dbConnect from "@/lib/mongodb";
import Filament from "@/models/Filament";
import "@/models/Nozzle";
import { resolveFilament } from "@/lib/resolveFilament";

function writeSection(
  lines: string[],
  name: string,
  settings: Record<string, string | null>,
  overrides?: Record<string, string>
) {
  lines.push(`[filament:${name}]`);

  const merged = { ...settings };
  if (overrides) {
    for (const [key, value] of Object.entries(overrides)) {
      if (value) merged[key] = value;
    }
  }

  for (const [key, value] of Object.entries(merged)) {
    if (value === null) {
      lines.push(`${key} = nil`);
    } else {
      lines.push(`${key} = ${value}`);
    }
  }

  lines.push("");
}

export async function GET() {
  await dbConnect();

  const filaments = await Filament.find()
    .sort({ name: 1 })
    .populate("calibrations.nozzle")
    .lean();

  // Build a parent lookup for resolving variants
  const parentMap = new Map<string, typeof filaments[number]>();
  for (const f of filaments) {
    if (!f.parentId) {
      parentMap.set(f._id.toString(), f);
    }
  }

  const lines: string[] = [];
  lines.push("# generated by Filament DB");
  lines.push("");

  for (const filament of filaments) {
    // Resolve inherited values for variants
    const resolved = filament.parentId
      ? resolveFilament(filament, parentMap.get(filament.parentId.toString()))
      : filament;

    const settings = (resolved.settings || {}) as Record<string, string | null>;
    const calibrations = resolved.calibrations as unknown as Array<{
      nozzle: { _id: string; name: string; diameter: number } | null;
      extrusionMultiplier: number | null;
      maxVolumetricSpeed: number | null;
      pressureAdvance: number | null;
      retractLength: number | null;
      retractSpeed: number | null;
      retractLift: number | null;
    }>;

    if (calibrations && calibrations.length > 0) {
      for (const cal of calibrations) {
        if (!cal.nozzle) continue;
        const nozzleSuffix = cal.nozzle.name;
        const sectionName = `${resolved.name} ${nozzleSuffix}`;

        const overrides: Record<string, string> = {};
        if (cal.extrusionMultiplier != null)
          overrides.extrusion_multiplier = cal.extrusionMultiplier.toString();
        if (cal.maxVolumetricSpeed != null)
          overrides.filament_max_volumetric_speed = cal.maxVolumetricSpeed.toString();
        if (cal.retractLength != null)
          overrides.filament_retract_length = cal.retractLength.toString();
        if (cal.retractSpeed != null)
          overrides.filament_retract_speed = cal.retractSpeed.toString();
        if (cal.retractLift != null)
          overrides.filament_retract_lift = cal.retractLift.toString();
        if (cal.pressureAdvance != null && settings.start_filament_gcode) {
          const gcode = settings.start_filament_gcode as string;
          overrides.start_filament_gcode = gcode.replace(
            /M572\s+S[\d.]+/,
            `M572 S${cal.pressureAdvance}`
          );
        }

        writeSection(lines, sectionName, settings, overrides);
      }
    } else {
      writeSection(lines, resolved.name, settings);
    }
  }

  const iniContent = lines.join("\n");

  return new NextResponse(iniContent, {
    headers: {
      "Content-Type": "text/plain",
      "Content-Disposition": 'attachment; filename="filament_profiles.ini"',
    },
  });
}
